name: build-drupal-and-deploy-to-s3
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: MilesChou/composer-action@master
        with:
          args: install --no-interaction --no-dev
