name: build-and-deploy-s3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rpinciuc/ci-builder@0.6
      - run: composer install --no-interaction --no-dev
